### ISSUE TITLE
Error on homepage and admin dashboard

### ISSUE THREAD

**Issue by olitre3** [DavidJClark/phpvms_5.5.x#10]
I am getting this error on both my homepage and admin dashboard
Warning: file_exists(): File name is longer than the maximum allowed path length on this platform (4096)

It points to line 118 in TemplateSet.class.php

I have checked there but there is nothing big there which looks like it is affecting it.

any help would be appriciated

Oli

**Comment by DavidJClark** [comment]
Fix - https://github.com/DavidJClark/phpvms_5.5.x/commit/552ea28460806ded24f316714d6d020a9dc6718b
