### ISSUE TITLE
Login file errors.

### ISSUE THREAD

**Issue by desertratps** [DavidJClark/phpvms_5.5.x#16]
This file phpvms_5.5.x/core/modules/Login/Login.php has still has "public function" not public static function" .

also all the templates called are for .tpl not .php

**Comment by DavidJClark** [comment]
None of the functions in the Login.php file should be statically called from anywhere in the system, at least no where I am aware of, this should be a non issue. The .tpl extension is also a non issue - it is replaced by the system early in the template build, you should be able to basically put anything you want for a file extension, the system will always replace it with a .php extension.
