### ISSUE TITLE
Missing Admin Links

### ISSUE THREAD

**Issue by flynryan692** [DavidJClark/phpvms_5.5.x#8]
I seem to be missing General Settings, Maintenance Options, Admin Activity Logs, and Template Diffs from the Admin links despite having full admin rights in the group Administrators. It is a fresh install and unedited..

**Comment by DavidJClark** [comment]
What platform is this on, it has not been reproduced on current stable php versions

**Comment by flynryan692** [comment]
We're running PHP 5.4 on linux. I figured it may be because this is the 5.5.x conversion, but switching to PHP 5.5 did not fix it either.
