### ISSUE TITLE
Problem in importing Schedules.

### ISSUE THREAD

**Issue by luizhvaisconcelos** [DavidJClark/phpvms_5.5.x#9]
DavidJClark good night, all right?

I am updating the system of my VA, VASP Version 2.1.936 of the system to 5.5.x
I'm finding problems when importing Schedules even adding a manually Schedules and making a backp and then trying to do an import of the same .csv file is experiencing an error:

-------------------------------------------------------------------------------------------------------------------------
"Warning: move_uploaded_file(/var/www/html/sisvasp/core/cacheschedules3.csv): failed to open stream: Permission denied in /var/www/html/sisvasp/admin/modules/Import/Import.php on line 334 Warning: move_uploaded_file(): Unable to move '/tmp/php3MuzSz' to '/var/www/html/sisvasp/core/cacheschedules3.csv' in /var/www/html/sisvasp/admin/modules/Import/Import.php on line 334 Warning: fopen(/var/www/html/sisvasp/core/cacheschedules3.csv): failed to open stream: No such file or directory in /var/www/html/sisvasp/admin/modules/Import/Import.php on line 336
-----------------------------------------------------------------------------------------------------------------------
Warning: fgetcsv () expects parameter 1 to be resource, boolean given in /var/www/html/sisvasp/admin/modules/Import/Import.php on line 352 The import process is complete, schedules 0 added, 0 updated, for a total of 0"

===============================================================================

Follows the model of csv file I'm importing:
code,flightnum,depicao,arricao,route,aircraft,flightlevel,distance,deptime,arrtime,flighttime,notes,price,flighttype,daysofweek,enabled," week1"," week2"," week3"," week4"
VSP,1001,SBGR,SUMU,"CGO1A CURSE UM788 ASDEK UA310 EAGLE/N0466F360 UA310 MLO UM792 TELAK TELA1C",PP-SFN,37000,848.053,00:35," 03:00"," 2.25"," COPA AMERICA TOUR IVAO SBFL 659NM CRR1R CRR UM540 PONCA PONC1A"," 7890"," P"," 0123456"," 1"," 0123456"," 0123456"," 0123456"," 0123456"

===============================================================================

Could you help me solve this problem?

Grateful!

**Comment by DavidJClark** [comment]
This is a permissions error on the server side.
